name: Publish Python Packages

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  build-dist:
    name: Build Python package distribution
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
        shell: bash

      - name: Build source and wheel distributions
        run: |
          python -m build --sdist --wheel --outdir dist

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: distributions
          path: |
            dist/*.whl
            dist/*.tar.gz

  publish-dist:
    needs: [build-dist]
    name: Publish Python distributions
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: distributions
          path: dist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
